"use client";

import { FormEvent } from "react";
import { Key, ShieldCheck } from "@phosphor-icons/react";

export type ImoleKey = { id: string; label: string; status: string; startingBalance: number; estimatedBalance: number; alertThreshold: number };
type FormState = { label: string; rawKey: string; startingBalance: string; alertThreshold: string };

export function AdminPanel({ keys, form, setForm, onSubmit, onUpdate }: { keys: ImoleKey[]; form: FormState; setForm: (value: FormState) => void; onSubmit: (event: FormEvent) => void; onUpdate: (id: string, action: "recharge" | "reset" | "toggle", amount?: number) => void }) {
  function update(field: keyof FormState, value: string) { setForm({ ...form, [field]: value }); }
  return <section className="full-route admin-route"><div className="route-header"><div><p className="kicker">Configuration serveur</p><h2>Pool Imọlẹ</h2><p>La clé maître est configurée dans <code>IMOLE_MASTER_API_KEY</code>. Le formulaire de réserve sert uniquement à suivre les soldes et les recharges manuelles.</p></div><span className="active-badge"><span className="online" /> Admin connecté</span></div><div className="admin-grid"><div className="panel admin-form"><div className="panel-heading"><div><p className="kicker">Clé maître</p><h2>Variable serveur</h2></div><ShieldCheck size={22} color="var(--forest)" /></div><p className="admin-hint">Pour des raisons de sécurité, la clé Imọlẹ n’est jamais saisie ni affichée dans cette page. Configurez-la dans Vercel avec <code>IMOLE_MASTER_API_KEY</code>, puis redéployez.</p></div><div className="panel admin-pool"><div className="panel-heading"><div><p className="kicker">Surveillance</p><h2>Clés enregistrées</h2></div><span className="pool-count">{keys.length}</span></div>{keys.length ? <div className="admin-key-list">{keys.map((item) => { const low = item.estimatedBalance <= item.alertThreshold; const exhausted = item.estimatedBalance <= 0 || item.status === "exhausted"; return <article className="admin-key-row" key={item.id}><div className="admin-key-title"><div><strong>{item.label}</strong><small>{item.status === "active" ? "Active" : item.status === "exhausted" ? "Épuisée" : "Inactive"}</small></div><span className={`admin-status ${exhausted ? "danger" : low ? "warning" : "ok"}`}>{exhausted ? "Épuisée" : low ? "À surveiller" : "Opérationnelle"}</span></div><div className="admin-key-metrics"><span>Solde estimé <b>{item.estimatedBalance.toLocaleString("fr-FR")} cauris</b></span><span>Seuil <b>{item.alertThreshold.toLocaleString("fr-FR")}</b></span></div><div className="admin-key-actions"><button type="button" onClick={() => { const value = window.prompt("Nombre de cauris réellement ajoutés sur Imọlẹ"); const amount = Number(value); if (Number.isFinite(amount) && amount > 0) onUpdate(item.id, "recharge", amount); }}>Ajouter des cauris</button><button type="button" onClick={() => onUpdate(item.id, "reset")}>Réinitialiser à 0</button><button type="button" onClick={() => onUpdate(item.id, "toggle")}>{item.status === "active" ? "Désactiver" : "Réactiver"}</button></div></article>; })}</div> : <div className="empty-state">Aucune réserve suivie. Le bonus et le proxy utilisent la clé maître configurée dans les variables serveur.</div>}</div></div></section>;
}


